"""added property type 
enums

Revision ID: 38a6ff0abb28
Revises: 50a296c9aa53
Create Date: 2025-11-20 16:47:38.253257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a6ff0abb28'
down_revision = '50a296c9aa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('APARTMENT', 'HOUSE', 'VILLA', 'CABIN', 'CONDO', 'STUDIO', 'LOFT', 'HOTEL_ROOM', 'HOTEL_SUITE', 'OTHER', name='propertytype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('APARTMENT', 'HOUSE', 'VILLA', 'CABIN', 'CONDO', 'STUDIO', 'LOFT', 'HOTEL_ROOM', 'HOTEL_SUITE', 'OTHER', name='propertytype'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
