"""Add is_host to User

Revision ID: 50a296c9aa53
Revises: 9f070465d1cc
Create Date: 2025-11-18 21:57:43.337130

"""
from alembic import op
import sqlalchemy as sa
import app.models.user as User


# revision identifiers, used by Alembic.
revision = '50a296c9aa53'
down_revision = '9f070465d1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_host', sa.Boolean(create_constraint=500), nullable=True))

    
    op.execute("UPDATE users SET is_host = CASE WHEN role = 'host' THEN 1 ELSE 0 END")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_host', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_host')

    # ### end Alembic commands ###
