"""add firebase fields

Revision ID: 5a8ea21a8d86
Revises: add_messaging_tables
Create Date: 2026-01-18 03:15:15.684197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5a8ea21a8d86'
down_revision = 'add_messaging_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_app_check_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_device_trusted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fcm_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')
        batch_op.drop_column('is_device_trusted')
        batch_op.drop_column('last_app_check_at')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cnic', sa.VARCHAR(length=15), nullable=True),
    sa.Column('cnic_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('verification_notes', sa.TEXT(), nullable=True),
    sa.Column('verified_at', sa.DATETIME(), nullable=True),
    sa.Column('verified_by_id', sa.INTEGER(), nullable=True),
    sa.Column('verification_photo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_email_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('cnic_image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_host', sa.BOOLEAN(), nullable=False),
    sa.Column('email_verified_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic')
    )
    op.create_table('_alembic_tmp_properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=11), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), nullable=False),
    sa.Column('bathrooms', sa.FLOAT(), nullable=False),
    sa.Column('max_guests', sa.INTEGER(), nullable=False),
    sa.Column('square_feet', sa.INTEGER(), nullable=True),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('service_fee_percentage', sa.FLOAT(), nullable=True),
    sa.Column('amenities', sqlite.JSON(), nullable=True),
    sa.Column('check_in_time', sa.TIME(), nullable=True),
    sa.Column('check_out_time', sa.TIME(), nullable=True),
    sa.Column('min_nights', sa.INTEGER(), nullable=True),
    sa.Column('max_nights', sa.INTEGER(), nullable=True),
    sa.Column('cancellation_policy', sa.VARCHAR(length=50), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('average_rating', sa.FLOAT(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
