"""empty message

Revision ID: bbed086e432c
Revises: fa312d2de3eb
Create Date: 2025-12-23 00:30:27.028601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bbed086e432c'
down_revision = 'fa312d2de3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_properties')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wishlist')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('_alembic_tmp_properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('property_type', sa.VARCHAR(length=11), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('bedrooms', sa.INTEGER(), nullable=False),
    sa.Column('bathrooms', sa.FLOAT(), nullable=False),
    sa.Column('max_guests', sa.INTEGER(), nullable=False),
    sa.Column('square_feet', sa.INTEGER(), nullable=True),
    sa.Column('price_per_night', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('cleaning_fee', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('service_fee_percentage', sa.FLOAT(), nullable=True),
    sa.Column('amenities', sqlite.JSON(), nullable=True),
    sa.Column('check_in_time', sa.TIME(), nullable=True),
    sa.Column('check_out_time', sa.TIME(), nullable=True),
    sa.Column('min_nights', sa.INTEGER(), nullable=True),
    sa.Column('max_nights', sa.INTEGER(), nullable=True),
    sa.Column('cancellation_policy', sa.VARCHAR(length=50), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('average_rating', sa.FLOAT(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
