"""
Payment API Routes for Flask
Add these routes to your Flask app
"""

from flask import Blueprint, request, jsonify, current_app
from app.services.safepay_service import SafepayService
from app.models.booking import Booking, BookingStatus # Import your Booking model
from extensions import db # Import db to save changes

payments_bp = Blueprint('payments', __name__, url_prefix='/api/payments')


@payments_bp.route('/safepay/create-session', methods=['POST'])
def create_safepay_session():
    data = request.get_json()
    amount = data.get('amount')
    booking_id = data.get('booking_id')
    
    if not amount or not booking_id:
        return jsonify({'error': 'Amount and booking_id required'}), 400

    booking = Booking.query.get(booking_id)
    if not booking:
         return jsonify({'error': 'Booking not found'}), 404

    service = SafepayService()
    
    try:
        # 1. Create v3 Tracker
        result = service.create_payment_tracker(amount=amount)
        tracker = result['tracker']
        
        # 2. Save Tracker to DB
        booking.payment_intent_id = tracker
        db.session.commit()

        return jsonify({
            'success': True,
            'tracker': tracker
        })
    except Exception as e:
        print(f"Safepay Init Error: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500


@payments_bp.route('/safepay/process', methods=['POST'])
def process_payment():
    data = request.get_json()
    tracker = data.get('tracker')
    
    # We now expect a TOKEN, not raw card data
    card_token = data.get('cardToken') 
    
    billing_data = data.get('billing', {})
    
    if not tracker or not card_token:
        return jsonify({'error': 'Missing tracker or card token'}), 400

    service = SafepayService()
    
    try:
        response = service.process_native_payment(tracker, card_token, billing_data)
        return jsonify({'success': True, 'data': response})
    except Exception as e:
        print(f"Payment Process Error: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500
    
@payments_bp.route('/cards/save', methods=['POST'])
def save_card_token():
    """
    Saves a card token generated by Basis Theory on the frontend.
    """
    data = request.get_json()
    
    # In a real app, get user_id from session/jwt
    # user_id = current_user.id 
    user_id = data.get('user_id') # Temporary for testing
    
    token_id = data.get('token_id')
    card_mask = data.get('card_mask')
    expiry_month = data.get('expiry_month')
    expiry_year = data.get('expiry_year')
    card_type = data.get('card_type', 'Unknown')

    if not all([user_id, token_id, card_mask, expiry_month, expiry_year]):
        return jsonify({'error': 'Missing required fields'}), 400

    try:
        new_card = CardToken(
            user_id=user_id,
            token_id=token_id,
            card_mask=card_mask,
            expiry_month=expiry_month,
            expiry_year=expiry_year,
            card_type=card_type
        )
        
        db.session.add(new_card)
        db.session.commit()

        return jsonify({'success': True, 'message': 'Card saved successfully'})

    except Exception as e:
        print(f"Error saving card: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500


# --- ENDPOINT 4: Serve Saved Cards ---
@payments_bp.route('/cards', methods=['GET'])
def get_user_cards():
    """
    Returns a list of saved cards for the user to select from.
    """
    # In a real app, get user_id from session/jwt
    # user_id = current_user.id
    user_id = request.args.get('user_id') # Passing as query param for testing

    if not user_id:
        return jsonify({'error': 'User ID required'}), 400

    try:
        cards = CardToken.query.filter_by(user_id=user_id).all()
        
        return jsonify({
            'success': True, 
            'cards': [card.to_dict() for card in cards]
        })

    except Exception as e:
        print(f"Error fetching cards: {e}")
        return jsonify({'success': False, 'error': str(e)}), 500

@payments_bp.route('/payment-success', methods=['GET'])
def payment_success_page():
    return "<h1>Payment Successful! Returning to app...</h1>", 200

@payments_bp.route('/payment-cancel', methods=['GET'])
def payment_cancel_page():
    return "<h1>Payment Cancelled. Returning to app...</h1>", 200